Date:
  Start:
    value: '2016-10-01'
  Type:
    value: Operational
GeoLoc:
  Location:
    AddrLn1: 64 HARLEY STREET
    Country: ENGLAND
    County: GREATER LONDON
    PostCode: W1G 7HB
    Town: LONDON
LastChangeDate:
  value: '2020-04-06'
Name: LINIA LTD
OrgId:
  assigningAuthorityName: HSCIC
  extension: DEV
  root: 2.16.840.1.113883.2.1.3.2.4.18.48
Rels:
  Rel:
  - Date:
      End:
        value: '2020-03-31'
      Start:
        value: '2016-10-01'
      Type:
        value: Operational
    Status:
      value: Inactive
    Target:
      OrgId:
        assigningAuthorityName: HSCIC
        extension: Q71
        root: 2.16.840.1.113883.2.1.3.2.4.18.48
      PrimaryRoleId:
        id: RO210
        uniqueRoleId: '168379'
    id: RE5
    uniqueRelId: '516610'
  - Date:
      Start:
        value: '2020-04-01'
      Type:
        value: Operational
    Status:
      value: Active
    Target:
      OrgId:
        assigningAuthorityName: HSCIC
        extension: QRV
        root: 2.16.840.1.113883.2.1.3.2.4.18.48
      PrimaryRoleId:
        id: RO261
        uniqueRoleId: '300794'
    id: RE5
    uniqueRelId: '693773'
Roles:
  Role:
  - Date:
      Start:
        value: '2016-10-01'
      Type:
        value: Operational
    Status:
      value: Active
    id: RO172
    primaryRole: 'true'
    uniqueRoleId: '288502'
Status:
  value: Active
metadata:
  org_id: DEV
  role_id: RO172
  status: Active
orgRecordClass: RC1
